# IT Academy - Data Science amb Python
## Tasca 4: Programació Numèrica

###  [Github Programació Numèrica](https://github.com/jesussantana/programacio_Numerica)

###  Exercici 1
- Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [1]:
import numpy as np
from numpy import random as rnd

def statisticalSummary(array):
    
    try:
        
        if array.ndim != 1:
            print("L'array té més d'una dimensió")
            
        else:
            print(f"El resum bàsic de l'array: {array}")
            print(f"Nombre d'elements: {len(array)}")
            print(f"La mitja és: {array.mean()}")
            print(f"La mitjana és: {np.median(array)}")
            print(f"El màxim de l'array és {format(array.max())}")
            print(f"El mínim de l'array és {format(array.min())}")
            print(f"La desviació estàndard és: {np.std(array)}")
            
    except  AttributeError:
        print("No és un Array")
        
statisticalSummary(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 8, 6, 5]))
statisticalSummary(np.array([[1, 3, 4, 2, 2, 7],[5, 2, 2, 1, 4, 1], [3, 3, 2, 2, 1, 1]]))
statisticalSummary('Python')

El resum bàsic de l'array: [ 1  2  3  4  5  6  7  8  9 10  8  6  5]
Nombre d'elements: 13
La mitja és: 5.6923076923076925
La mitjana és: 6.0
El màxim de l'array és 10
El mínim de l'array és 1
La desviació estàndard és: 2.6131211925327738
L'array té més d'una dimensió
No és un Array


###  Exercici 2
- Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [2]:
def square(num):
    
    try:
        
        rnd.seed(1234)
        array = rnd.randint(100,size=(num,num))
        return array
    
    except TypeError:
        
        print("Ha de ser un nombre natural")

print(square(1))
print(square(2))
print(square(3))
print(square('hola'))

[[47]]
[[47 83]
 [38 53]]
[[47 83 38]
 [53 76 24]
 [15 49 23]]
Ha de ser un nombre natural
None
