# IT Academy - Data Science amb Python
## Tasca 4: Programació Numèrica

###  [Github Programació Numèrica](https://github.com/jesussantana/programacio_Numerica)
[![forthebadge made-with-python](http://ForTheBadge.com/images/badges/made-with-python.svg)](https://www.python.org/)  
[![Made withJupyter](https://img.shields.io/badge/Made%20with-Jupyter-orange?style=for-the-badge&logo=Jupyter)](https://jupyter.org/try) 

###  Exercici 1
- Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [1]:
import numpy as np
from numpy import random

def statycal(arr):
    
    if arr.ndim > 1:
        print ("El array debe ser de 1 dimensión")
        
    else:
        print("Número de observaciones: ", len(arr))
        print("Max: ", arr.max())
        print("Min: ", arr.min())
        print("Media: ",arr.mean())
        print("Mediana: ", np.median(arr))
        print("Desv est: ", np.std(arr))
        print("Q 25: ", np.percentile(arr, 25))
        print("Q 75: ", np.percentile(arr, 75))
        
arr = np.array([1,3,5,6,4,43,2,6,78,3,4,7,87])

statycal(arr)

Número de observaciones:  13
Max:  87
Min:  1
Media:  19.153846153846153
Mediana:  5.0
Desv est:  29.000918165428313
Q 25:  3.0
Q 75:  7.0


###  Exercici 2
- Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [2]:
def square(n):
    print(random.randint(100, size = (n, n)))

square(2)
square(14)

[[69  4]
 [ 6 65]]
[[84 59 38 78 50 72 31 42 33 68 36 62 82 53]
 [75 15 97 12 45 71 16 85 88 86 63 91 15 63]
 [ 6 24 78 76 68 66 91 70 21 51 97 82 40 99]
 [56 22 80 90 30 33 75 59 16  8 87 44 14 51]
 [25 75  1  1 19 80 99  1 12 36  0 60 30 31]
 [16 76 48 99 53 55 45 93 52 24 55 39 66 15]
 [74 83 96 89 78 66 50 15 74 81 72 29 11 13]
 [ 5 42 54 38 37 93 62  5 86 29 64 19 90 96]
 [24 97 25 64 15 59 43 84 67 89 25 38 51 26]
 [ 7 28  7  7 84 27 64  9 38  9 82 55 67 26]
 [ 7 71 45 15 58 46 17 18 25  8 71  6 40 20]
 [81 83  5 26 78 34  7 11 47  5 87 92 90 72]
 [34 75 76  0 99 16  7 42 40 48 49 38  3 59]
 [38 37  2 77  9 33 87 15 70 55 19 42 89 28]]


###  Exercici 3
- Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [3]:
def rowsColumns(array):
    
    if array.ndim != 2:
        print ("Introduce una array de 2 dimensiones")
        
    else:
        rows = np.sum (array, axis = 1)
        columns = np.sum (array, axis = 0)
        print("Total por filas: ", rows)
        print("Total por columnas: ", columns)

rowsColumns(np.array([[3,4,5], [6,7,8,]]))

Total por filas:  [12 21]
Total por columnas:  [ 9 11 13]


###  Exercici 4
- Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [4]:
def correlation(x, y):
    
    if len(x) != len(y):
        print('Los vectores deben tener la misma dimensión')
        
    else:
        covariance = np.sum([(x-np.mean(x))*(y-np.mean(y))])/(len(x)-1)
        
        stdX =(np.sum((x-np.mean(x))**2)/(len(x)-1))**(1/2)
        stdY =(np.sum((y-np.mean(y))**2)/(len(y)-1))**(1/2)
        
        print(covariance/stdX/stdY)

a = random.randint(100, size = (50))
b = random.randint(10, size = (50))

correlation (a, b)

0.01378433110080725
